<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>ModularAudience_favicon.ico</ApplicationIcon>
    <PackageIcon>ModularAudience_favicon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Helpers\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <None Remove="Helpers\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ModularAudience_favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\ModularAudience.Audio\Resources\ModularAudience_favicon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="alarmclockkisser.DragNDrop.Forms" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModularAudience.Audio\ModularAudience.Audio.csproj" />
    <ProjectReference Include="..\ModularAudience.Cuda\ModularAudience.Cuda.csproj" />
    <ProjectReference Include="..\ModularAudience.Generators\ModularAudience.Generators.csproj" />
    <ProjectReference Include="..\ModularAudience.Onnx\ModularAudience.Onnx.csproj" />
  </ItemGroup>

</Project>