<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ManagedCuda-13" Version="13.0.64" />
    <PackageReference Include="ManagedCuda-CUFFT" Version="13.0.64" />
    <PackageReference Include="ManagedCuda-NVRTC" Version="13.0.64" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModularAudience.Audio\ModularAudience.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Kernels\PTX\" />
  </ItemGroup>

</Project>
